services:
  mongo:
    image: mongo:7
    container_name: engweb_ex1_mongo
    volumes:
      - mongo_ex1_data:/data/db
    networks:
      - ex1-net

  api:
    restart: unless-stopped
    build: ./api
    container_name: engweb_ex1_api
    ports:
      - "17000:17000"
    environment:
      - PORT=17000
      - MONGO_URL=mongodb://mongo:27017/jogostabuleiro
    depends_on:
      - mongo
    networks:
      - ex1-net

networks:
  ex1-net:
    driver: bridge

volumes:
  mongo_ex1_data:
